### ISSUE TITLE
All roads rendered as one-way

### ISSUE THREAD

**Issue by ondryk** [mapbox/osm-bright#109]
Hello,
I've imported country PBF taken from geofabrik.de and imported it via:

osm2pgsql --number-processes 8 --slim -d cz-sk -C 8192 --hstore kosovo.pbf

After that I set up osm-bright scheme using https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/ and noticed, that since zoom 16, all roads are marked with "one-way" arrow sing. Mapnik scheme rendered tiles from OSM servers are correct.

osm-bright 
![k1](https://cloud.githubusercontent.com/assets/12694770/12216653/af6332f6-b6e9-11e5-84f3-f587e1d02c0b.png)

mapnik:
![k2](https://cloud.githubusercontent.com/assets/12694770/12216661/ccf24064-b6e9-11e5-9163-1a47630707c6.png)

I tried several countries with the same result. Did I miss some kind of scheme setup?
Thank you.
Ondrej

**Comment by sylven310** [comment]
Hi Ondrej,

I got the same issue and fixed it in the osm-bright/labels.mss file:
Near the end, there is a ONE-WAY ARROWS section that I've replaced with the following:

#motorway_label[oneway='yes'][zoom>=16],
#mainroad_label[oneway='yes'][zoom>=16],
#minorroad_label[oneway='yes'][zoom>=16] {
  marker-placement:line;
  marker-max-error: 0.5;
  marker-spacing: 200;
  marker-file: url(img/icon/oneway.svg);
  [zoom=16] { marker-transform: "scale(0.5)"; }
  [zoom=17] { marker-transform: "scale(0.75)"; }
}

#motorway_label[oneway='-1'][zoom>=16],
#mainroad_label[oneway='-1'][zoom>=16],
#minorroad_label[oneway='-1'][zoom>=16] {
  marker-placement:line;
  marker-max-error: 0.5;
  marker-spacing: 200;
  marker-file: url(img/icon/oneway-reverse.svg);
  [zoom=16] { marker-transform: "scale(0.5)"; }
  [zoom=17] { marker-transform: "scale(0.75)"; }
}

I've not managed to merge the two interesting values '-1' and 'yes' in the same block but I guess this is possible...
The key thing here is that osm2pgsql creates the data with almost all oneway values unset (i.e. NULL). This must be correctly understood by the oneway selector here. The current one is [oneway!=0] which also selects ways with NULL oneway, causing the arrows to be shown almost everywhere.
Hope this helps. Please note, because of my lack of knowledge with this, I'm not sure this is a correct fix for all osm-bright users. The maintainer may think differently and provide a different and certainly better fix.

**Comment by ondryk** [comment]
Thank you sylven, I actually managed it in similar way I found on original OSM theme github repo and created [pull request](https://github.com/mapbox/osm-bright/pull/111) from it. So for me it works and it is up to maintainer.
